language: node_js
node_js:
- '7'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install
before_script:
- npm link .
script:
- ./ci/tmplify.js
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/commit_push.js
- ./ci/travis/publish.js

after_success:
- ./ci/travis/publish.js
env:
  secure: "GMx42cxotfFSKdD4qx5viomEEYRaNSk6Baj+VyAcrQiNMkgDtI4ieirSzdBR0Kn8MYibccSTaJjGlki4RkoRxSRIvSG9KmT0vqkm2fjakKeWj0CqzKt9XJgFGWsqDXTvgsz1t48s2RuKEUE46iIoJiJ+rW7Hoxd4ypfM7HnsaYO7V8uL9iSxJOapfsWGCGeNQHhJx6QgXNisbz5KGfdV1wG5ZBOZlYpMjIKoJZfifT6PL9urbsO8+jVaJqIm4lY2CVxDrEHU0SieXzVEH7aAhUu3cZa438IjT3LuQiGISW8z9u8KRHVOYv2PYDG9eQOQB0dUzhgnV+t3ofMNxW4OCrxhPzMwt/pZGis/YYbKWTZBVG7x5TuBbpzspo5NScemmn0XdPI0GR9NqUWBqHYlC3lA8riA9aZSKL1MTvkJt8swEssqn+nLFTq7ygHae0V5vmwKR98ATskMCdKIEnIMiSwcNHxpx4uaZ06TwcfoGPkr34S0l9GMBCbUInLOz/UV/u1sicCKQXfkefx5EIWFaYBCHFfYXakmjY1Yf7iB+oPP3p76ZwComT9NMTSMd3VExwRY9YkvlXAjlwdRK5KMLm57tBwhggbBY6AEcRZSXXd9SrB+6q+oDzefNwUxwmghA/UnmFsfvx3BjO7T12ObBxzQSdafMYRjCDqgFu25zXs="
env:
  secure: "UZWL+K4gPYgdLbzGA/5uV8rfw8Y+VZj2Q3B1VM2yI6t+RMheyuuc9EcYrf4ElwsxjCsWHbXEVWvTxWNVIxHWz/h5H2QRuCf8PhNvPDLVup017/nFdaP68mJ0o51ceW8JZMSwr9hUGHhcqti/Z0nolf9l8k6syxhaPeqXIldG8NeW+/tL8qLYIRA4oDiaE6m3v6+enlVMRWW6ya3mcRHbPXbvTixrefNY2ldMbk2ioK7xecKX/bA2B6eoV9Nk79DpIkFhTBH895y3Cz4qdEHxFT6uS5/7qFTHBVTMy542d8RWHRMU31RLFSJRTRJ2QYjdnWzk/nOV2Q9NqvNifUVK0fuewUeB5fz+1Gx8+gsyjWPSf+uMuFjgjcSybMKz6Kv3UJ2ltTWPRgklCCwTlu4QZ9jJTuiNgeSyIN54DoK5Y2M/aO9w8WVRq/OkFr7I7KHIi6Zr6FRfqZou0b1kTOdp4Q+kk/vBd9ep/WBI6DwtRv6ZmSvBMnZdZRJAhU5KE9cy8sl3SPzjpWss9mKTEcNKbwgRJZLvXulvV3kJvKD1llEMC0QXp3ZzR3YmLfYcaPmPNTR3fyRAtzDpzEzRjDGiWfgcqvZy9Biz5LaUHN00IXWXSLnMMXABb/mbyHENJ+smwLw+04ZREzSfoxEv0/96EyUeCK+t8BRvoFzWgX3gM/k="
