language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/doc.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: nCgHdRm904VynsRHxOBUxP6hqol/0CSz5z2N/L7uUyDk1z+Z8nt5uDrd9rHsVjVnBMHmqG+/10O2cQff/jrXJ8/4O3EDjtQy4EWcjFBF7hI65QNuJK3q9JOZjHT19z9XwbWVrnxOBXRbDDZJrdWeLzxt3TFhdfUll19xbwh1afdZ9VTJIWeXwcNyykZYOnhizjvz2kgK4t9kJ5XO/3oofGV8XW47ogkzU/tNiHET1ggWyeN8NFjMv7J+EJ/JnprJ34bkdCVSaN5Tqt1KK3IQmYVS0WUqi0tHYAa/pyzDrPTzBkxt468XH2rvMemyD23SZcFBYdTzCs1mmldnIpvwzuNDyT3V/FSeE2kjYUIK3lQIa+b4KgJI313/QRWlBTcA2iSH5HADuty2mC+BfOX0psG/TvFtNAtHx4JfrB0eRmxkAxpkeu85ik0r7PVOi8yXKR4QODYSaTSJsxI6BgHoYb2bXDUy6tFUo/AHJtp8HBG5QOgicc/er0pWHtGa8V/NYAVCSkPosiOy+R6VUfkZbg7yXuoQIxwhTw1D6oZ95xVffcZ5RjWkF9GrCkcXium1xZk2dSdAFTpryyNYsPrgjMrvRdepueJRM6MqnbqGViER4QgJoftw64psBewCgWpJVqUGWtMGm/btte8rWm1Iqr6XkFGs6kiFmz4zOd/7NuE=
  - secure: eeJsW7uSRMY2Hfn7jc8kXsuLlRFnNKmR/Mag8JU/tTO41envZ926gjmy6EfMqDb6wBktK0+EXK4Wf4nfhrwPLz8pG4SmFYBNd1vuepSdSUb7HdINWZFXCchXJSwcmUch6Zo0OSVodlb5amRXUiG/Gtrl/7j2dMBqx6y2zfs7X2HSuizKqgnF1FSZjQtgcPjE1VcqoqXo8aQGtqqcJASHcvxvmzupK8Afe6VkJptJd/P449I1lvEYM+Brdh+AYMLjo1wXXAlNQLbbj+ESg8a1G0z+WaKQBYb+N52iC0bYMFKtvA1GCGYBFc12n9TlNLoX28AQgtV26TO1oGKdF+Tedc5FX2ayKnBXiMSW6nWsC6JpZaUfaLC/UI8HHkJ+X5EjLCkuUJ1oRJ2Ds2g1+Uydj0bTs+ao/dm0WcV/6EVwuHYcBdX0mhGA5ZrUxVP1eexHeFaBiPG7k/FJ6aFrucSWB2xC4z7gP8x9rX8KHQWxvvGdyKu15XC2TCZksxCNCMWg8nf3e+FL9yfMJlwS7oFS3/mBgPBf+JvnkxQT1oMrDzP0NBLCSmiIy1jgGMDIIUJ14p19ClPvzxgiZuXcAvcEuOerUJRiZVhIZ9Z09UcaDaIZ/KjtJkNUQNb6chh3hcx3t+admhCSbJ1LD3MZSO2mIfW5SLqsSbId5of2YZ8g+QQ=
