language: node_js
node_js:
- '7'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install
before_script:
- npm link .
script:
- ./ci/tmplify.js
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/commit_push.js
- ./ci/travis/publish.js

after_success:
- ./ci/travis/publish.js
env:
  secure: "GMx42cxotfFSKdD4qx5viomEEYRaNSk6Baj+VyAcrQiNMkgDtI4ieirSzdBR0Kn8MYibccSTaJjGlki4RkoRxSRIvSG9KmT0vqkm2fjakKeWj0CqzKt9XJgFGWsqDXTvgsz1t48s2RuKEUE46iIoJiJ+rW7Hoxd4ypfM7HnsaYO7V8uL9iSxJOapfsWGCGeNQHhJx6QgXNisbz5KGfdV1wG5ZBOZlYpMjIKoJZfifT6PL9urbsO8+jVaJqIm4lY2CVxDrEHU0SieXzVEH7aAhUu3cZa438IjT3LuQiGISW8z9u8KRHVOYv2PYDG9eQOQB0dUzhgnV+t3ofMNxW4OCrxhPzMwt/pZGis/YYbKWTZBVG7x5TuBbpzspo5NScemmn0XdPI0GR9NqUWBqHYlC3lA8riA9aZSKL1MTvkJt8swEssqn+nLFTq7ygHae0V5vmwKR98ATskMCdKIEnIMiSwcNHxpx4uaZ06TwcfoGPkr34S0l9GMBCbUInLOz/UV/u1sicCKQXfkefx5EIWFaYBCHFfYXakmjY1Yf7iB+oPP3p76ZwComT9NMTSMd3VExwRY9YkvlXAjlwdRK5KMLm57tBwhggbBY6AEcRZSXXd9SrB+6q+oDzefNwUxwmghA/UnmFsfvx3BjO7T12ObBxzQSdafMYRjCDqgFu25zXs="
