// Code generated by coz. DO NOT EDIT.
/**
 * Module mappings
 * @module mappings
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const SceneMapping_ = require('./SceneMapping')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.SceneMapping = _d(SceneMapping_)

module.exports = {
  SceneMapping: _d(SceneMapping_),
}
