// Code generated by coz. DO NOT EDIT.
/**
 * Server controllers
 * @module controllers
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get AppCtrl () { return _d(require('./AppCtrl')) },
}
