// Code generated by coz. DO NOT EDIT.
/**
 * Module mappings
 * @module mappings
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get ControllerMapping () { return _d(require('./ControllerMapping')) },
  get ResourceMapping () { return _d(require('./ResourceMapping')) },
}
