// Code generated by coz. DO NOT EDIT.
/**
 * Db resource classes
 * @module resources
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get RoomResource () { return _d(require('./RoomResource')) },
}
