// Code generated by coz. DO NOT EDIT.
/**
 * Constant variables
 * @module constants
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const AppConsts_ = require('./AppConsts')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.AppConsts = _d(AppConsts_)

module.exports = {
  AppConsts: _d(AppConsts_),
}
