// Code generated by coz. DO NOT EDIT.
/**
 * Constant variables
 * @module constants
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get AppConsts () { return _d(require('./AppConsts')) },
}
